### PR TITLE
Unify data access for ARIMA and GES models

### PR DESCRIPTION
**Pull request by mastoffel**
The PR does two things:

1) Merge two separate data-access modules into one model_data_access.py which now lives in cropcore.
2) Makes the data access for ARIMA flexible: Tables, columns and joins can now be specified in the existing config.ini, which is now configured to obtain the same two data tables / columns which were previously hardcoded.

### CODE REVIEW

**Comment by dsj976** [comment]
Will close this and open another pull request in order to run the latest GitHub Action tests.

**Comment by dsj976** [comment]
Undoing this - this was unnecessary

**Comment by dsj976** [comment]
thanks Martin, this looks very good, great work!

**Comment by mastoffel** [comment]
Thanks David! Glad it worked!

**Pull request merged**
